### PR TITLE
0504

### PR DESCRIPTION
**Pull request by 2021Vincent**
1. refactor ShowMapAll in GameMap.cpp
2. add Collision in Human.cpp
3. refactor bool Item::Collide()
4. move GetX() GetY() from MainHuman.cpp to Human.cpp
5. add LIB_KEY_CHASE event, change oni1 to normal_oni in mygame.h
6. for class Oni, it's able to transit in different maps
7. resolve to item layer prooblem

### CODE REVIEW

**Comment by 2021Vincent** [comment]
this is a bug

**Comment by kyynk** [comment]
ok

**Comment by kyynk** [comment]
你修好了再跟我說一下

**Comment by 2021Vincent** [comment]
@kyynk

**Review by kyynk — APPROVED** [review]
LGTM

**Comment by kyynk** [comment]
他說重複的code太多ㄌ

**Comment by 2021Vincent** [comment]
this is its destiny

**Pull request merged**
