### PR TITLE
0503

### PR DESCRIPTION
**Pull request by 2021Vincent**
1.change nChar == VK_RETURN to nChar == VK_SPACE in dialog.cpp
2. add GameMap::ShowMapAll polymorphism in GameMap.cpp
3. add enum TriggerType in item.h
4. add MIKA_NOTOK_E, MIKA_OK_E, MIKA_SCARE_E event
5. change void ObjMove::SetPlayerPos to void ObjMove::StorePlayerPos

### CODE REVIEW

**Comment by kyynk** [comment]
image

**Comment by 2021Vincent** [comment]
hey

**Comment by 2021Vincent** [comment]
i need your review

**Comment by 2021Vincent** [comment]
@kyynk

**Review by kyynk — APPROVED** [review]
LGTM

**Pull request merged**
